version: "3.7"
services:
  client:
    build:
      context: ./manuka-client
  # listener:
  #   build:
  #     context: ./manuka-listener
  nginx:
    image: nginx:alpine
    networks:
      - internet
      - internal_routing
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - postgres
    secrets:
      - postgres_password
  server:
    build:
      context: ./manuka-server
    networks:
      - internal_routing
      - postgres
    secrets:
      - postgres_password
secrets:
  postgres_password:
    file: ./docker/secrets/postgres_password
networks:
  internet:
  internal_routing:
    internal: true
  postgres:
    internal: true