version: "3.7"
services:
  client:
    build:
      context: ./manuka-client
  listener-linkedin:
    build:
      context: ./manuka-listener
    environment:
      COMPANY_NAME: Axcel Productions
      LISTENER_ID: 2
      LISTENER_TYPE: 2
      MESSAGES_CACHE_FILE: messages_cache.json
      GOOGLE_CREDENTIALS_FILE: /run/secrets/google_credentials
      GOOGLE_OAUTH2_TOKEN_FILE: /run/secrets/google_oauth2_token
    networks:
      - internal_routing
    restart: always
    secrets:
      - google_credentials
      - google_oauth2_token
  listener-login:
    build:
      context: ./manuka-listener
    environment:
      COMPANY_NAME: Axcel Productions
      LISTENER_ID: 1
      LISTENER_TYPE: 1
    networks:
      - internal_routing
    restart: always
  nginx:
    image: nginx:alpine
    networks:
      - internet
      - internal_routing
    restart: always
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - postgres
    restart: always
    secrets:
      - postgres_password
  server:
    build:
      context: ./manuka-server
    depends_on:
      - postgres
    networks:
      - internal_routing
      - postgres
    restart: always
    secrets:
      - postgres_password
secrets:
  postgres_password:
    file: ./docker/secrets/postgres_password
  google_credentials:
    file: ./docker/secrets/google_credentials.json
  google_oauth2_token:
    file: ./docker/secrets/google_oauth2_token.json
networks:
  internet:
  internal_routing:
    internal: true
  postgres:
    internal: true
