version: "3.7"
services:
  client:
    build:
      dockerfile: Dockerfile-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    networks:
      - internal_routing
    volumes:
      - ./manuka-client:/manuka-client
      - /manuka-client/node_modules
  nginx:
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
  server:
    build:
      dockerfile: Dockerfile-dev
    networks:
      - internet
    volumes:
      - ./manuka-server:/manuka-server
